CUDA_VISIBLE_DEVICES=1 accelerate launch --config_file accelerate_config.json train_ootd.py \
    --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
    --mixed_precision="fp16" \
    --output_dir="output/logs/train_ootd" \
    --dataset_name="SaffalPoosh/VITON-HD-test" \
    --resolution="512" \
    --learning_rate="1e-5" \
    --train_batch_size="1" \
    --dataroot="../data/VITON-HD" \
    --train_data_list="subtrain_0.1.txt" \
    --test_data_list="subtest_0.1.txt" \
    --num_train_epochs="100" \
    --checkpointing_steps="500" \
    --use_8bit_adam \
    --gradient_checkpointing \
    --enable_xformers_memory_efficient_attention \
    --validation_steps="100" \
    --inference_steps="50" \
    --log_grads \
    --report_to="wandb" 