CUDA_VISIBLE_DEVICES=1 python /home/dwang/miniconda3/envs/ootd/bin/accelerate launch \
    --config_file accelerate_config.json train_ootd.py \
    --pretrained_model_name_or_path="checkpoints/ootd/" \
    --mixed_precision="fp16" \
    --output_dir="output/logs/train_ootd" \
    --dataset_name="SaffalPoosh/VITON-HD-test" \
    --resolution="512" \
    --dataroot="/opt/disk1/dwang/sci/DVTON/data/updated-VITON-HD" \
    --train_data_list="subtrain_0.1.txt" \
    --test_data_list="subtrain_0.1.txt" \
    --use_8bit_adam \
    --gradient_checkpointing \
    --enable_xformers_memory_efficient_attention \
    --validation_steps="30" \
    --inference_steps="50" \
    --log_grads \
    --report_to="wandb" \
    --seed="42" \